package config

object Color {
  const val PRIMARY_GREEN = "mediumseagreen"
  const val TEXT_GREY = "#b3b9c5"
  const val INPUT_BOX_GREY_BORDER = "#b3b9c5"
  const val BACKGROUND_BLACK = "#202020"
  const val BOTTOM_DIVIDER_PLAYBACK_QUEUE_ITEM = "#323232"
  const val BACKGROUND_SHADOW_GRADIENT_DARK = "#101010"
  const val BACKGROUND_SHADOW_GRADIENT_LIGHT = "#202020"
  const val BACKGROUND_CONTENT_GRID_IMAGE = "#2F2F2F"

  const val BACKGROUND_PLAYBACK_QUEUE_ITEM_ACTIVELY_PLAYING = PRIMARY_GREEN
  const val BACKGROUND_PLAYBACK_QUEUE_ITEM_NOT_ACTIVELY_PLAYING = "#323232"

  const val PROGRESS_BAR_BACKGROUND = "#323232"
  const val PROGRESS_BAR_PROGRESS = PRIMARY_GREEN
  const val PROGRESS_BAR_DOT = PRIMARY_GREEN

  const val FLOATING_QUEUE_MENU_CLEAR_BUTTON_TEXT = "#202020"

  const val FLOATING_MESSAGE_TEXT = "#202020"
}
